### ISSUE TITLE
Getting Intermittent failure when launching Python kernels.

### ISSUE THREAD

**Issue by sshuklao** [jupyter-server/enterprise_gateway#1048]
## Description
When we launch IPykernel using launcher python script, we are getting below error and not seeing web socket connection request in JEG logs.
## Screenshots / Logs
```
[D 2022-03-14 17:15:54.328 EnterpriseGatewayApp] Connecting to: tcp://127.0.0.1:58137
[D 2022-03-14 17:15:54.331 EnterpriseGatewayApp] Connecting to: tcp://127.0.0.1:44721
[I 2022-03-14 17:15:54.333 EnterpriseGatewayApp] Kernel started: cc019cef-6e1b-472d-b817-dabdaac15a5c, name: python38
[D 2022-03-14 17:15:54.333 EnterpriseGatewayApp] Kernel args: {'env': {'PATH': '/opt/ibm/scala/bin:/opt/ibm/jdk/bin:/home/spark/.local/bin:/home/spark/bin:/opt/ibm/spark/bin:/opt/ibm/conda/R/bin:/opt/ibm/conda/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'KERNEL_ID': 'cc019cef-6e1b-472d-b817-dabdaac15a5c', 'KERNEL_USERNAME': 'spark'}, 'kernel_headers': {}, 'kernel_name': 'python38'}
[I 2022-03-14 17:15:54.333 EnterpriseGatewayApp] Culling kernels with idle durations > 43200 seconds at 60 second intervals ...
[I 220314 17:15:54 web:2243] 201 POST /api/kernels (::1) 322.94ms
[I 220314 17:15:54 web:2243] 200 GET /api/kernels/cc019cef-6e1b-472d-b817-dabdaac15a5c (::1) 1.11ms
[I 220314 17:16:00 web:2243] 200 GET /api/kernels/cc019cef-6e1b-472d-b817-dabdaac15a5c (172.30.227.55) 0.84ms
[D 2022-03-14 17:16:01.067 EnterpriseGatewayApp] activity on cc019cef-6e1b-472d-b817-dabdaac15a5c: error
[D 2022-03-14 17:16:01.070 EnterpriseGatewayApp] activity on cc019cef-6e1b-472d-b817-dabdaac15a5c: status (starting)
```
## Environment

- Enterprise Gateway Version : 2.5.0
- Platform: Yarn Client

Proxy used :   
"process_proxy": {
    "class_name": "enterprise_gateway.services.processproxies.distributed.DistributedProcessProxy"
  },

**Comment by kevin-bates** [comment]
There isn't a whole lot to go by here.  I suspect the interesting debug statements (produced during the launch of the kernel) are above this particular snapshot.

Information that would be included in that output is which process proxy is being used along with various interactions with the underlying resource manager, etc.  The fact that you're getting some "error" output via the kernel messages does imply the kernel process started to some extent, but there's really not enough information here to troubleshoot further.

You indicate BOTH Yarn and Kubernetes in your platform description.  If this implies both are in use simultaneously, then this is something we have never tried (e.g., running EG in kubernetes, hitting a YARN cluster) but is one reason we implemented the [single-port response address](https://github.com/jupyter-server/enterprise_gateway/pull/877) which was released in EG 2.6.0 (and I see you're using 2.5.0), but I shouldn't speculate on that configuration.

Please include the complete set of logging information starting with messages that resemble the following:
```
[D 2022-03-10 16:34:26.441 EnterpriseGatewayApp] RemoteMappingKernelManager.start_kernel: spark_python_yarn_cluster, kernel_username: gateway
[D 2022-03-10 16:34:26.456 EnterpriseGatewayApp] Instantiating kernel 'Spark - Python (YARN Cluster Mode)' with process proxy: enterprise_gateway.services.processproxies.yarn.YarnClusterProcessProxy
```

**Comment by sshuklao** [comment]
@kevin-bates updated above description.

**Comment by surbhibakhtiyar** [comment]
@kevin-bates Following are the complete logs
```
{"message":"**********************************"}
{"message":"80cbb96c-d1a3-4751-a032-b830a8dd64f0 Wed Mar 23 08:06:39 UTC 2022 Start Jupyter kernel gateway"}
{"message":"[D 2022-03-23 08:06:40.586 EnterpriseGatewayApp] Searching ['/home/spark/shared', '/home/spark/.jupyter', '/home/spark/.local/etc/jupyter', '/usr/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files"}
{"message":"[D 2022-03-23 08:06:40.587 EnterpriseGatewayApp] Looking for jupyter_config in /etc/jupyter"}
{"message":"[D 2022-03-23 08:06:40.587 EnterpriseGatewayApp] Looking for jupyter_config in /usr/local/etc/jupyter"}
{"message":"[D 2022-03-23 08:06:40.587 EnterpriseGatewayApp] Looking for jupyter_config in /usr/etc/jupyter"}
{"message":"[D 2022-03-23 08:06:40.587 EnterpriseGatewayApp] Looking for jupyter_config in /home/spark/.local/etc/jupyter"}
{"message":"[D 2022-03-23 08:06:40.587 EnterpriseGatewayApp] Looking for jupyter_config in /home/spark/.jupyter"}
{"message":"[D 2022-03-23 08:06:40.587 EnterpriseGatewayApp] Looking for jupyter_config in /home/spark/shared"}
{"message":"[D 2022-03-23 08:06:40.591 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /etc/jupyter"}
{"message":"[D 2022-03-23 08:06:40.591 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /usr/local/etc/jupyter"}
{"message":"[D 2022-03-23 08:06:40.591 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /usr/etc/jupyter"}
{"message":"[D 2022-03-23 08:06:40.591 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /home/spark/.local/etc/jupyter"}
{"message":"[D 2022-03-23 08:06:40.591 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /home/spark/.jupyter"}
{"message":"[D 2022-03-23 08:06:40.591 EnterpriseGatewayApp] Looking for jupyter_enterprise_gateway_config in /home/spark/shared"}
{"message":"[D 220323 08:06:40 selector_events:54] Using selector: EpollSelector"}
{"message":"[I 2022-03-23 08:06:40.601 EnterpriseGatewayApp] Jupyter Enterprise Gateway 2.5.0 is available at http://*:8888"}
{"message":"[I 220323 08:06:41 web:2243] 200 GET /api/kernels (::1) 1.48ms"}
{"message":"[D 2022-03-23 08:06:41.026 EnterpriseGatewayApp] RemoteMappingKernelManager.start_kernel: python38, kernel_username: spark"}
{"message":"[D 2022-03-23 08:06:41.026 EnterpriseGatewayApp] Using user-provided kernel_id: 80cbb96c-d1a3-4751-a032-b830a8dd64f0"}
{"message":"[D 2022-03-23 08:06:41.271 EnterpriseGatewayApp] Instantiating kernel 'Python 3.8 with Spark' with process proxy: enterprise_gateway.services.processproxies.processproxy.LocalProcessProxy"}
{"message":"[D 2022-03-23 08:06:41.273 EnterpriseGatewayApp] Starting kernel (async): ['/opt/ibm/kernelScript/python/python-kernel-wrapper.sh', 'python3.8', '/home/spark/.local/share/jupyter/runtime/kernel-80cbb96c-d1a3-4751-a032-b830a8dd64f0.json', '{response_address}', '0..0', 'lazy']"}
{"message":"[D 2022-03-23 08:06:41.273 EnterpriseGatewayApp] Launching kernel: 'Python 3.8 with Spark' with command: ['/opt/ibm/kernelScript/python/python-kernel-wrapper.sh', 'python3.8', '/home/spark/.local/share/jupyter/runtime/kernel-80cbb96c-d1a3-4751-a032-b830a8dd64f0.json', '{response_address}', '0..0', 'lazy']"}
{"message":"[D 2022-03-23 08:06:41.273 EnterpriseGatewayApp] BaseProcessProxy.launch_process() env: {'PATH': '/opt/ibm/conda/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'KERNEL_ID': '80cbb96c-d1a3-4751-a032-b830a8dd64f0', 'KERNEL_USERNAME': 'spark', 'PYSPARK_PYTHON': '/opt/ibm/conda/miniconda/bin/python', 'SPARK_HOME': '/opt/ibm/spark', 'INSTALL_DIR': '/opt/ibm', 'WORK_DIR': '/home/spark/shared', 'PYTHONPATH': '/home/spark/user_home:/home/spark/shared/user-libs/python:/home/spark/shared/conda/envs/python/lib/python/site-packages:/opt/ibm/conda/miniconda/lib/python/site-packages:/opt/ibm/third-party/libs/python3:/opt/ibm/image-libs/python3:/opt/ibm/spark/python:/opt/ibm/spark/python/lib/py4j-0.10.9-src.zip', 'CONDARC': '/home/spark/shared/user-libs/python/.condarc', 'CONDA_ENVS_PATH': '/home/spark/shared/conda/envs', 'CONDA_PKGS_DIRS': '/home/spark/shared/conda/envs/python/pkgs', 'PYTHONSTARTUP': '/opt/ibm/kernelScript/python/shell.py', 'PIXIEDUST_LIBS_PATH': '/home/spark/shared/user-libs/spark2/', 'HB_RUNTIME_PROVIDER': 'Hummingbird', 'HOME': '/home/spark/shared', 'JAVA_HOME': '/opt/ibm/jdk', 'SCALA_HOME': '/opt/ibm/scala', 'SERVICE_HOME': '/home/spark/shared', 'KERNEL_GATEWAY': '1', 'KERNEL_LANGUAGE': 'python3', 'EG_IMPERSONATION_ENABLED': 'False'}"}
{"message":"[I 2022-03-23 08:06:41.279 EnterpriseGatewayApp] Local kernel launched on '172.30.143.27', pid: 86, pgid: 86, KernelID: 80cbb96c-d1a3-4751-a032-b830a8dd64f0, cmd: '['/opt/ibm/kernelScript/python/python-kernel-wrapper.sh', 'python3.8', '/home/spark/.local/share/jupyter/runtime/kernel-80cbb96c-d1a3-4751-a032-b830a8dd64f0.json', '{response_address}', '0..0', 'lazy']'"}
{"message":"[D 2022-03-23 08:06:41.280 EnterpriseGatewayApp] Connecting to: tcp://127.0.0.1:48729"}
{"message":"[D 2022-03-23 08:06:41.281 EnterpriseGatewayApp] Connecting to: tcp://127.0.0.1:35339"}
{"message":"[I 2022-03-23 08:06:41.283 EnterpriseGatewayApp] Kernel started: 80cbb96c-d1a3-4751-a032-b830a8dd64f0, name: python38"}
{"message":"[D 2022-03-23 08:06:41.284 EnterpriseGatewayApp] Kernel args: {'env': {'PATH': '/opt/ibm/scala/bin:/opt/ibm/jdk/bin:/home/spark/.local/bin:/home/spark/bin:/opt/ibm/spark/bin:/opt/ibm/conda/R/bin:/opt/ibm/conda/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'KERNEL_ID': '80cbb96c-d1a3-4751-a032-b830a8dd64f0', 'KERNEL_USERNAME': 'spark'}, 'kernel_headers': {}, 'kernel_name': 'python38'}"}
{"message":"[I 2022-03-23 08:06:41.284 EnterpriseGatewayApp] Culling kernels with idle durations > 43200 seconds at 60 second intervals ..."}
{"message":"[I 220323 08:06:41 web:2243] 201 POST /api/kernels (::1) 259.80ms"}
{"message":"[I 220323 08:06:41 web:2243] 200 GET /api/kernels/80cbb96c-d1a3-4751-a032-b830a8dd64f0 (::1) 0.77ms"}
{"message":"[I 220323 08:06:46 web:2243] 200 GET /api/kernels/80cbb96c-d1a3-4751-a032-b830a8dd64f0 (172.30.14.129) 0.97ms"}
{"message":"[I 220323 08:06:46 web:2243] 200 GET /api/kernels/80cbb96c-d1a3-4751-a032-b830a8dd64f0 (172.30.14.129) 0.84ms"}
{"message":"[D 2022-03-23 08:06:47.527 EnterpriseGatewayApp] activity on 80cbb96c-d1a3-4751-a032-b830a8dd64f0: error"}
{"message":"[D 2022-03-23 08:06:47.530 EnterpriseGatewayApp] activity on 80cbb96c-d1a3-4751-a032-b830a8dd64f0: status (starting)"}
{"message":"[I 220323 08:06:48 web:2243] 200 GET /api/kernels/80cbb96c-d1a3-4751-a032-b830a8dd64f0 (172.30.14.185) 0.92ms"}
{"message":"[I 220323 08:06:48 web:2243] 200 GET /api/kernels/80cbb96c-d1a3-4751-a032-b830a8dd64f0 (172.30.14.185) 0.77ms"}
{"message":"[D 2022-03-23 08:07:41.338 EnterpriseGatewayApp] Polling every 60 seconds for kernels idle > 43200 seconds..."}
{"message":"[D 2022-03-23 08:07:41.338 EnterpriseGatewayApp] kernel_id=80cbb96c-d1a3-4751-a032-b830a8dd64f0, kernel_name=python38, last_activity=2022-03-23 08:06:47.530057+00:00"}
```
cc @sshuklao

**Comment by kevin-bates** [comment]
Hi @surbhibakhtiyar - thank you for the update.  I have a couple of questions

I see you are using `LocalProcessProxy`...
> {"message":"[D 2022-03-23 08:06:41.271 EnterpriseGatewayApp] Instantiating kernel 'Python 3.8 with Spark' with process proxy: enterprise_gateway.services.processproxies.processproxy.LocalProcessProxy"}

Yet are including _portions_ of the `RemoteProcessProxy` base class parameters...
> {"message":"[D 2022-03-23 08:06:41.273 EnterpriseGatewayApp] Starting kernel (async): ['/opt/ibm/kernelScript/python/python-kernel-wrapper.sh', 'python3.8', '/home/spark/.local/share/jupyter/runtime/kernel-80cbb96c-d1a3-4751-a032-b830a8dd64f0.json', '{response_address}', '0..0', 'lazy']"}

where these `'{response_address}', '0..0', 'lazy'` correspond to the `--RemoteProcessProxy.response-address`, `--RemoteProcessProxy.port-range`, and `--RemoteProcessProxy.spark-context-initialization-mode` parameters respectively.

As a result, I suspect the kernel is starting, but then encountering an error, probably attempting to reply to the response address with its connection information.  However, since EG will not create a socket to accept remote connection information when launching a local kernel (by virtue of `LocalProcessProxy`), the kernel winds up in this limbo state.

Could you please include the `kernel.json` file associated with your `Python 3.8 with Spark` kernel?  If your JSON file defers to a shell script, please include that script as well.

These additional parameters should not be included when the `LocalProcessProxy` is in use, so this could be implying an issue in EG as well, although I haven't seen this.  I suspect the `kernel.json` (and any associates) will help.

**Comment by sshuklao** [comment]
we are seeing intermittent failure when connecting notebook using nb2kg as well, Please check the below logs.
```
[I 15:00:42.502 NotebookApp] Kernel started: 7038d9f0-f17c-459d-be78-71fbcb7ffd1e
[E 15:00:43.888 NotebookApp] Uncaught exception POST /api/sessions (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
        type=mtype))
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/lib/python3.6/site-packages/nb2kg/managers.py", line 385, in create_session
        session_id, path=path, name=name, type=type, kernel_id=kernel_id,
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/lib/python3.6/site-packages/nb2kg/managers.py", line 414, in save_session
        session_id, path=path, name=name, type=type, kernel_id=kernel_id
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/lib/python3.6/site-packages/nb2kg/managers.py", line 440, in get_session
        session = yield super(SessionManager, self).get_session(**kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/lib/python3.6/site-packages/nb2kg/managers.py", line 483, in row_to_model
        kernel = yield self.kernel_manager.get_kernel(row['kernel_id'])
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/lib/python3.6/site-packages/nb2kg/managers.py", line 184, in get_kernel
        response = yield fetch_kg(kernel_url, method='GET')
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/conda/lib/python3.6/site-packages/nb2kg/managers.py", line 75, in fetch_kg
        response = yield client.fetch(url, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
    tornado.httpclient.HTTPClientError: HTTP 502: Bad Gateway
[W 15:00:43.894 NotebookApp] Unhandled error
[E 15:00:43.894 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|ea78ab34|2257e16aad1b4a4c60db2836f19a7bca|1649255634",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/json",
      "Origin": "http://localhost:8888/",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15",
      "Referer": "http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python38",
      "Content-Length": "92",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1649255871|23:username-localhost-8888|44:ZTdmZjU3Y2M0ZDJiNGJkYThjMmZiNGYxYWQ2M2UyMTc=|0e830d01c4c728b25d0328d4852629b0086f0e87431b01ac11746f6d0447a064\"; _xsrf=2|ea78ab34|2257e16aad1b4a4c60db2836f19a7bca|1649255634"
    }
[E 15:00:43.895 NotebookApp] 500 POST /api/sessions (172.17.0.1) 15847.90ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python38
[I 15:02:26.902 NotebookApp] Saving file at /Untitled.ipynb
```

**Comment by sshuklao** [comment]
We are seeing websocket connection call is not coming into logs but when we restarted the kernel, will be able to see websocket call into log file.
[Uploading Untitled.txt…]()

**Comment by kevin-bates** [comment]
Let's focus on one issue at a time please.  Looking at your `kernel.json` and the wrapper (and I don't see `run.sh`) you're referencing remote-specific parameters for a local kernel invocation.  You need to either set a remote process proxy class in your kernel.json file or should remove the three parameters I referenced above.  When no process proxy class is specified the `LocalProcessProxy` is used - which is meant to support the default (non-remote) case, which I don't believe you want.

I suspect you want to use either [`DistributedProcessProxy`](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/operators/deploy-distributed.html) to launch a kernel amongst a set of remote hosts (via ssh) or [`YarnClusterProcessProxy`](https://jupyter-enterprise-gateway.readthedocs.io/en/latest/operators/deploy-yarn-cluster.html) to let a YARN resource manager determine on which host the kernel should run.

**Comment by sshuklao** [comment]
@kevin-bates we are not seeing this issue now, thanks.

**Comment by kevin-bates** [comment]
Thanks for the update @sshuklao.  Was this something addressed via configuration or other changes?  Perhaps others can benefit from what was done to get things working.
